Repository sopra-fs24-group-28/spotify-memory-server, pull requests merged in 2024-05, with the labels that each got.

#149 148 provide profile picture url for users
  src/main/java/ch/uzh/ifi/hase/soprafs24/entity/User.java
  src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/PlayerDTO.java
  src/main/java/ch/uzh/ifi/hase/soprafs24/service/AuthService.java
  src/main/java/ch/uzh/ifi/hase/soprafs24/service/SpotifyService.java
  src/main/java/ch/uzh/ifi/hase/soprafs24/service/UserService.java
  src/test/java/ch/uzh/ifi/hase/soprafs24/service/UserServiceTest.java
Labels: Task, Back-End

#152 #151 Adjust numOfSets if playlist is too short
  src/main/java/ch/uzh/ifi/hase/soprafs24/service/GameService.java
  src/main/java/ch/uzh/ifi/hase/soprafs24/service/SpotifyService.java
  src/test/java/ch/uzh/ifi/hase/soprafs24/service/GameServiceIntegrationTest.java
Labels: Task, Back-End

#160 #84 Streak Powerup
  src/main/java/ch/uzh/ifi/hase/soprafs24/model/game/Game.java
  src/main/java/ch/uzh/ifi/hase/soprafs24/service/GameService.java
  src/main/java/ch/uzh/ifi/hase/soprafs24/websocket/dto/helper/WSGameChanges.java
  src/test/java/ch/uzh/ifi/hase/soprafs24/service/GameServiceTest.java
Labels: Task, Back-End

#180 #175 pause music on leave or turn change
  src/main/java/ch/uzh/ifi/hase/soprafs24/service/GameService.java
  src/main/java/ch/uzh/ifi/hase/soprafs24/service/SpotifyService.java
  src/test/java/ch/uzh/ifi/hase/soprafs24/service/GameServiceTest.java
Labels: bug, Back-End

#173 #171 Null Pointer Exception in case the Auth header Is not available caught & fixed turner by queueing the request
  .gitignore
  src/main/java/ch/uzh/ifi/hase/soprafs24/event/InactiveRequestEvent.java
  src/main/java/ch/uzh/ifi/hase/soprafs24/rest/webFilter/ManualSecurityFilter.java
  src/main/java/ch/uzh/ifi/hase/soprafs24/service/DeferredExecutionService.java
  src/main/java/ch/uzh/ifi/hase/soprafs24/service/GameService.java
  src/test/java/ch/uzh/ifi/hase/soprafs24/rest/webFilter/ManualSecurityFilterTest.java
  src/test/java/ch/uzh/ifi/hase/soprafs24/service/GameServiceTest.java
Labels: bug, Back-End

#181 Cleanup (Closes #174)
  src/main/java/ch/uzh/ifi/hase/soprafs24/constant/user/PlayerState.java
  src/main/java/ch/uzh/ifi/hase/soprafs24/entity/Player.java
  src/main/java/ch/uzh/ifi/hase/soprafs24/model/game/CardCollection.java
  src/main/java/ch/uzh/ifi/hase/soprafs24/model/game/GameParameters.java
  src/main/java/ch/uzh/ifi/hase/soprafs24/model/game/Playlist.java
  src/main/java/ch/uzh/ifi/hase/soprafs24/model/game/Turn.java
  src/main/java/ch/uzh/ifi/hase/soprafs24/model/helper/Change.java
  src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/GameDTO.java
  src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/LobbyGameDto.java
  src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/LobbyOverviewDto.java
  src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/PlayerDTO.java
  src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/PlaylistDTO.java
  src/main/java/ch/uzh/ifi/hase/soprafs24/rest/dto/UserPostDTO.java
  src/main/java/ch/uzh/ifi/hase/soprafs24/service/UserService.java
  src/test/java/ch/uzh/ifi/hase/soprafs24/controller/GameControllerTest.java
  src/test/java/ch/uzh/ifi/hase/soprafs24/service/CardCollectionTest.java
  src/test/java/ch/uzh/ifi/hase/soprafs24/service/StatsServiceTest.java
Labels: Back-End

#201 #189 fix failed dependency when start is double-clicked
  src/main/java/ch/uzh/ifi/hase/soprafs24/service/GameService.java
Labels: bug, Back-End

#203 196 write readme for server repo
  README.md
  contributions.md
Labels: documentation, Back-End
